baseURL = "https://works.nunogodinho.com/"
languageCode = "en-us"
title = "Nuno Godinho"
theme = "hugo-creative-portfolio-theme"

[taxonomies]
  category = "categories"
  tag = "tags"
  year = "years"

[permalinks]
  works = "/:filename/"
  events = "/:filename/"

[params]
  style = "blue"
  copyright = "&copy;2020 Nuno Godinho"

  [[params.navlinks]]
  name = "works"
  url = "/works"
  home = true

  [[params.navlinks]]
  name = "events"
  url = "/events"

 [[params.navlinks]]
  name = ""
  url = ""

 [[params.navlinks]]
  name = "video"
  url = "/categories/video"

 [[params.navlinks]]
  name = "audio"
  url = "/categories/audio"

 [[params.navlinks]]
  name = "photo"
  url = "/categories/photo"

 [[params.navlinks]]
  name = "object"
  url = "/categories/object"

 [[params.navlinks]]
  name = "words"
  url = "/categories/words"

 [[params.navlinks]]
  name = "others"
  url = "/categories/others"

 [[params.navlinks]]
  name = ""
  url = ""

  [[params.navlinks]]
  name = "about me"
  url = "/about"
